language: node_js
node_js:
- '6.1'
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
deploy:
  app: bikedeboa-api
  provider: heroku
  api_key:
    secure: ElWErDkYjfjesTY1EzRnbZEs8BdEKFhNHBTY5ZMc9r+w9Z0KKOxR4+oCmSYq5B+pF7/XoCKlB82OgX8ocW7I8GoRtVtl+HWFjwjw5a+WEbguKp0cYV9lKDxXJ/67eCfZoQ+gg0+D0xrOXq68GYwE1uXmmuvSTK46C5ecykZfaEq1QzCD57nmSSz9MnZmpCjtVolNPvP4iT++BR5tXsZVftKT3CTW5Q/OCCbR/xK2LnS3fsjCvc7pw1ZPUXQJKb36a/jN5nwZ+aZk7V4GIS3Pk9tVHHpE+nCPg2LF34sMVokJusVeNijoqWHIRvyC/S6cE5oe653qkPdQFvoEAM0h+DFiGapRVLD+Jn4/IxnR/l8QtdX8KqeycpPjAbfrFMYhLP43EeGxNNiuFqGd+GA1G4W6OKsidf7DD7AjLS2AjmLZ4BPSgBZASbGwnRRD908byp8JL9ohUN4dXO8s9sg2loYVtzRhTrQVVtbjDtRgmj6TIfswc9USOjU5wSZ5ptMirpZ+gE3QfUje0VFDSuAhDjeLMX6l2RSWNTAuA36zfM/1DEj9PmdQdID2Orjo4lsdCYpLtIdumbTOUYG/0EdETdWxQYF+ObfQfmKzHrmxpaxcBktbB2z6yCH2/Ys3MGLeH5MlBPJT5+IbGHLLcyqRhkVot30bwUkvo4i4OCYhYYQ=
